# Generated by Django 2.0.3 on 2018-06-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_phone', models.CharField(max_length=11)),
                ('CMND', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('number_pay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SIM.SIM')),
            ],
        ),
    ]
