# Generated by Django 2.0.3 on 2018-06-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0002_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='number_pay',
            field=models.CharField(max_length=11),
        ),
    ]
